name: Test

on:
  workflow-dispatch:

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: "${{ secrets.ACCESS_TOKEN }}"

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - run: npm i -D prettier
    - run: npm install
    - run: npm test
    - run: npx prettier -w index.js
    - run: npx prettier -w test/**/*.js
    - run: |
        git config --global user.name "dimaslanjaka"
        git config --global user.mail "dimaslanjaka@gmail.com"
        git add .
        git commit -m "refactor: prettier fix"
    - run: git push
      continue-on-error: true





